export const COUNT_SCORE = "COUNT_SCORE";
export const RESET_SCORE = "RESET_SCORE";

export const GET_ALL_QUS_REQUEST_SEND = "GET_ALL_QUS_REQUEST_SEND";
export const GET_ALL_QUS_REQUEST_SUCCESS = "GET_ALL_QUS_REQUEST_SUCCESS";
export const GET_ALL_QUS_REQUEST_FAIL = "GET_ALL_QUS_REQUEST_FAIL";

export const SUBMIT_ANSWER = "SUBMIT_ANSWER";
